config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    resources :providers, only: [:show, :index, :new, :create] do
      resources :courses, only: [:show, :index]
    end
    resources :courses, only: [:show, :index, :new, :create]
    resources :feed_backs, only: [:create]
    get '/about', to: 'welcome#about', as: :about
    get '/contacts', to: 'welcome#contacts', as: :contacts
    get '/profile', to: 'welcome#profile', as: :profile
    root to: 'welcome#home'
  end
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :without_locale_root
  get '/*path', to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
      constraints: {path: /(?!((#{I18n.available_locales.join("|")}|assets))\/).*/}, format: false
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: [:profile]

  def home
    @all_subjects = Subject.includes(:courses).all
    @all_providers = Provider.moderated.all
  end

  def about; end

  def contacts; end

  def profile; end
end

app/views/welcome/_provider_preview.haml
.provider-item
  .item
    .item-ads-grid
      //.item-badge-grid.premium-ads
      //  %a{href: '#'} Featured Ads
      //.item-badge-grid.featured-ads
      //  %a{href: '#'} Featured Ads
      .item-img-grid
        = image_tag provider.icon_url(:medium), alt: 'Edit Entry', class: 'img-responsive img-center'
      .item-title
        %a{href: provider_path(provider)}
          %h4= provider.name
      .item-meta
        %ul
          %li.item-date
            %i.fa.fa-book
            = t('labels.courses', count: provider.courses.size)
          -#%li.item-cat
          -#  %i.fa.fa-bars
          -#  = provider.subjects.first(2).join(', ')
          %li.item-location
            %a{href: provider.site, target: '_blank'}
              %i.fa.fa-external-link
              = provider.site
      .product-footer
        .item-price-grid.pull-left
          %h3
            %i.fa{ class: "fa-#{provider.currency.downcase}" }
            = number_to_currency(provider.average_price, unit: '')
          - if provider.free_content
            %span= t('labels.providers.has_free_content')
        .item-action-grid.pull-right
          %ul
            %li
              %a.btn.btn-default.btn-sm{'data-placement' => 'top', 'data-toggle' => 'tooltip', href: '#', title: 'Save Favorite'}
                %i.fa.fa-heart
            %li
              %a.btn.btn-success.btn-sm{'data-placement' => 'top', 'data-toggle' => 'tooltip', href: '/', title: 'Show Details'}
                %i.fa.fa-eye
-#
  .owl-item{style: 'width: 250px;'}
    .item
      .item-ads-grid
        .item-badge-grid.featured-ads
          %a{href: '#'} Featured Ads
        .item-img-grid
          %img.img-responsive.img-center{alt: '', src: 'assets/img/products/product-1.jpg'}/
        .item-title
          %a{href: '/course/1'}
            %h4 Lenovo A326 Black 4GB RAM
        .item-meta
          %ul
            %li.item-date
              %i.fa.fa-clock-o
              Today 10.35 am
            %li.item-cat
              %i.fa.fa-bars
              %a{href: '/course/1'} Electronics
              ,
              %a{href: '/course/1'} Smartphone
            %li.item-location
              %a{href: '/course/1'}
                %i.fa.fa-map-marker
                Manchester
            %li.item-type
              %i.fa.fa-bookmark
              New
        .product-footer
          .item-price-grid.pull-left
            %h3 $ 100
            %span Negotiable
          .item-action-grid.pull-right
            %ul
              %li
                %a.btn.btn-default.btn-sm{'data-placement' => 'top', 'data-toggle' => 'tooltip', href: '#', title: 'Save Favorite'}
                  %i.fa.fa-heart
              %li
                %a.btn.btn-success.btn-sm{'data-placement' => 'top', 'data-toggle' => 'tooltip', href: '/', title: 'Show Details'}
                  %i.fa.fa-eye
    .owl-item{style: 'width: 250px;'}
      .item
        .item-ads-grid
          .item-badge-grid.premium-ads
            %a{href: '#'} Featured Ads
          .item-img-grid
            %img.img-responsive.img-center{alt: '', src: 'assets/img/products/product-6.jpg'}/
          .item-title
            %a{href: 'detail.html'}
              %h4 Samsung Tab 3 V 116
          .item-meta
            %ul
              %li.item-date
                %i.fa.fa-clock-o
                Today 10.35 am
              %li.item-cat
                %i.fa.fa-bars
                %a{href: '/course/1'} Electronics
                ,
                %a{href: '/course/1'} Smartphone
              %li.item-location
                %a{href: '/course/1'}
                  %i.fa.fa-map-marker
                  Manchester
              %li.item-type
                %i.fa.fa-bookmark
                New
          .product-footer
            .item-price-grid.pull-left
              %h3 $ 100
              %span Negotiable
            .item-action-grid.pull-right
              %ul
                %li
                  %a.btn.btn-default.btn-sm{'data-placement' => 'top', 'data-toggle' => 'tooltip', href: '#', title: 'Save Favorite'}
                    %i.fa.fa-heart
                %li
                  %a.btn.btn-success.btn-sm{'data-placement' => 'top', 'data-toggle' => 'tooltip', href: 'detail.html', title: 'Show Details'}
                    %i.fa.fa-eye

app/views/welcome/about.html.haml
%section.main
  .container
    .row
      .col-md-12
        .post
          .post-title
            %h2= t('labels.about')
          .post-body
            %p= t('labels.about_page.start')
            %p= t('labels.about_page.goal')
            %p= t('labels.about_page.help', link: link_to(t('labels.about_page.link'), new_user_registration_path)).html_safe
            %p= t('labels.about_page.sign')

app/views/welcome/contacts.html.haml
%section.main
  .container
    .row
      .col-md-12
        .widget
          .widget-header
            %h3= t('labels.contacts_page.sending_message')
          .widget-body
            = simple_form_for(:feed_back, url: feed_backs_path) do |f|
              %p= t('labels.contacts_page.hint')
              .row
                .col-xs-4
                  %input.form-control.input-lg{placeholder: t('labels.contacts_page.name'), type: 'text', name: 'feed_back[name]', autofocus: true}
                .col-xs-4
                  %input.form-control.input-lg{placeholder: 'Email', type: 'text', name: 'feed_back[email]', autofocus: true}
              %br
              .row
                .col-xs-12
                  %textarea.form-control{placeholder: t('labels.contacts_page.writing_here'), rows: '8', required: 'required', name: 'feed_back[content]'}
              %br
              .row
                .col-xs-12
                  %button.btn.btn-lg.btn-custom.pull-right= t('labels.contacts_page.submit')

app/views/welcome/home.html.haml
- if notice.present?
  .alert.alert-success{role: 'alert'}= notice
- if alert.present?
  .alert.alert-info{role: 'alert'} = alert

%section.hero
  .container.text-center
    %h1.hero-title= t('titles.main_page_h1')
    %p.hero-description.hidden-xs= t('titles.search_p')
    .row.hero-search-box
      %form{'accept-charset' => 'utf-8', enctype: 'multipart/form-data', action: courses_path, method: 'get'}
        .col-md-3.col-sm-3.search-input
          %select.form-control.input-lg.search-second{name: 'subject'}
            %option{selected: 'selected', value: 'all'}= t('labels.all_subjects')
            - @all_subjects.each do |subject|
              %option{value: subject.id}= subject.name
        .col-md-3.col-sm-3.search-input
          %select.form-control.input-lg.search-second{name: 'provider'}
            %option{selected: 'selected', value: 'all'}= t('labels.all_providers')
            - @all_providers.each do |provider|
              %option{value: provider.id}= provider.name
        .col-md-3.col-sm-3.search-input
          %input.form-control.input-lg.search-first{placeholder: t('labels.lucky'), type: 'text', name: 'title'}
        .col-md-3.col-sm-3.search-input
          %button.btn.btn-custom.btn-block.btn-lg{type: 'submit'}
            %i.fa.fa-search
%section.main
  .container
    .row
      .col-md-8.col-sm-8
        .row
          - @all_subjects.each do |subject|
            .col-xs-4.col-sm-3
              .shortcut
                %a{href: courses_path(subject: subject.id)}
                  = image_tag subject.icon_url(:medium), class: 'img-responsive img-center'
                %a{href: courses_path(subject: subject.id)}
                  %h3= subject.name
                %span.total-items
                  %i.fa.fa-book
                  = t('labels.courses', count: subject.courses.size)

        .row
          .col-md-12
            .section-header
              %h2= t('labels.best_providers')
            #featured-products{style: 'opacity: 1; display: block;'}
              - @all_providers.first(3).each do |provider|
                = render 'provider_preview', provider: provider

      .col-md-4.col-sm-4
        - unless current_user
          .widget
            .widget-header
              %h3= t('devise.sign_up')
            .widget-body
              = simple_form_for(:user, url: registration_path(:user)) do |f|
                .form-group
                  .input-group
                    %span.input-group-addon.addon-login
                      %i.fa.fa-user
                    %input.form-control.input-login{placeholder:  I18n.t('labels.email'), required: 'required', type: 'text', name: 'user[email]', autofocus: true}
                .form-group
                  .input-group
                    %span.input-group-addon.addon-login
                      %i.addon.fa.fa-lock
                    %input.form-control.input-login{placeholder: "#{t('labels.password')}(#{t('devise.min_length_hint', count: 8)})", required: 'required', type: 'password', name: 'user[password]'}
                .form-group
                  .input-group
                    %span.input-group-addon.addon-login
                      %i.addon.fa.fa-lock
                    %input.form-control.input-login{placeholder: I18n.t('labels.password_confirmation'), required: 'required', type: 'password', name: 'user[password_confirmation]'}
                %input.btn.btn-custom.btn-block{type: 'submit', value: I18n.t('labels.signup')}

        .widget
          .widget-header
            %h2= t('titles.w_courses_providers')
          .widget-body
            %ul.trends
              - @all_providers.each do |provider|
                %li
                  = link_to courses_path(providers: provider.id) do
                    = provider.name
                    %span.badge= provider.courses_count
        .banner-widget
          %img.img-responsive{alt: 'banner', src: asset_path('temp_banner.png')}
.counter
  .container
    .row
      .col-md-3
        .item-counter
          %span.item-icon
            %i.fa.fa-university
          .item-count= Provider.moderated.count
          %span.item-info= t('labels.providers_list')
      .col-md-3
        .item-counter
          %span.item-icon
            %i.fa.fa-book
          .item-count= Course.moderated.count
          %span.item-info= t('labels.courses_list')
      .col-md-3
        .item-counter
          %span.item-icon
            %i.fa.fa-tags
          .item-count= Subject.count
          %span.item-info= t('labels.subjects_list')
      .col-md-3
        .item-counter
          %span.item-icon
            %i.fa.fa-users
          .item-count= User.count + Course.count + Provider.count + Subject.count
          %span.item-info= t('labels.members_list')

app/views/welcome/profile.html.haml
- if notice.present?
  .alert.alert-success{role: 'alert'}= notice
- if alert.present?
  .alert.alert-danger{role: 'alert'}= alert.join('. ')


%section.main

  -#.account-header
  -#  .container
  -#    .row
  -#      .col-sm-4.col-md-3.col-lg-2
  -#        / User avatar
  -#        .profile_avatar
  -#          %img.img-responsive{:alt => "avatar", :src => "assets/img/people/gie.jpg"}/
  -#      .col-sm-8.col-md-9.col-lg-10
  -#        .profile_summary
  -#          / User name
  -#          %h3.profile_name John Doe
  -#          / User status
  -#          %p Hello.. I'am a frontend developer.
  -#          / Contact
  -#          %a.btn.btn-primary.btn-warning.btn-sm{:href => "index.html"}
  -#            %i.fa.fa-sign-out
  -#            Sign Out
  / / .profile__summary
  / / .row
  / / .container
  .container
    .row
      = render 'layouts/user_profile_menu'
      .col-md-9.col-sm-9
        .panel.panel-default
          .panel-heading
            %h4.panel-title= t('labels.my_profile')

          .panel-body